# 에러 핸들링

## try..catch와 에러 핸들링

#### try...catch 문법
```javascript
try {
    //코드..
} catch {
    //에러 핸들링
}
```
>try..catch는 오직 런타입 에러에만 동작
>>try..catch는 실행 가능한(runnable) 코드에만 동작<br/>유효한 코드에서 발생하는 에러만 처리. 이러한 에러를 '런타임 에러'혹은 '예외'라고 부른다.
>try..catch는 동기적으로 동작한다.
>>setTimeout처럼 '스케줄 된' 코드에서 발생한 예외는 try..catch에서 잡아낼 수 없다.
```javascript
try {
  setTimeout(function() {
    noSuchVariable; // 스크립트는 여기서 죽음
  }, 1000);
} catch (e) {
  alert( "작동 멈춤" );
}
```
>해결
```javascript
setTimeout(function() {
  try {
    noSuchVariable; // 이제 try..catch에서 에러를 핸들링 할 수 있음
  } catch {
    alert( "에러를 잡았습니다!" );
  }
}, 1000);
```
#### 직접 에러를 만들어서 던지기

```javascript
let json = '{"age":30}';

try {
    let user = JSON.parse(json);

    if(!user.name) {
        throw new SyntaxError('불완전한 데이터: 이름 없음');
    }

    alert(user.name);
} catch(e) {
    alert('JSON Error:' + e.message); //JSON Error: 불완전한 데이터: 이름 없음
}
```
#### 에러 다시 던지기
예기치 않은 에러가 try {...} 블록 안에서 발생 할 수 있다.

```javascript
let json = '{"age":30}';

try {
    let user = JSON.parse(json);

    if(!user.name) {
        throw new SyntaxError('불완전한 데이터: 이름 없음');
    }

    bglabla(); //예상치 못한 에러

    alert(user.name);
} catch(e) {
    if(e instanceof SyntaxError) {
        alert('JSON Error:' + e.message);
    } else {
        throw e;
    }
}
```

```javascript

function readData() {
    let json = '{"age":30}';

    try {
        let user = JSON.parse(json);

        if(!user.name) {
            throw new SyntaxError('불완전한 데이터: 이름 없음');
        }

        bglabla(); //예상치 못한 에러

        alert(user.name);
    } catch(e) {
        if(e instanceof SyntaxError) {
            alert('JSON Error:' + e.message);
        } else {
            throw e;
        }
    }
}

try {
    readData();
} catch(e) {
    alert('External catch got:' + e); //에러를 잡음
}
```

#### try..catch..finally
finally절은 무언가를 실행하고, 실행결과에 상관없이 실행을 완료하고 싶을 경우 사용

>try..catch..finally 안의 변수는 지역 변수...

>finally 와 return
try블록안에 return이 있어도 finally 실행 후 빠져 나간다.

<hr/>

## 커스텀 에러와 에러 확장

throw의 인수엔 아무런 제약이 없기 때문에 커스텀 에러 클래스는 반드시 Error를 상속할 필요가 없다. 그렇지만 Error를 상속받아 커스텀 에러 클래스를 만들게 되면 obj instanceof Error를 사용해서 에러 객체를 식별할 수 있다는 장점이 생김. 이런 장점 때문에 맨땅에서 커스텀 에러 객체를 만드는 것보다 Error를 상속받아 에러 객체를 만드는 것이 나음.

#### 에러 확장하기
자체 기준 에러를 만들어 본다. 지금부터 이 에러를 ValidationError라고 한다.

```javascript
class ValidationError extends Error {
    constructor(message) {
        super(message);
        this.name = 'ValidationError';
    }
}

function test() {
    throw new ValidationError('에러 발생!');
}

try {
    test();
} catch(err) {
    alert(err.name); //ValidateionError
    alert(err.message); //에러 발생!
    alert(err.statck); //각 행 번호가 있는 중첩된 호출들의 목록
}
```

```javascript
class ValidationError extends Error {
    constructor(message) {
        super(message);
        this.name = 'ValidationError';
    }
}

//사용법
function readUser(json) {
    let user = JSON.parse(json);

    if(!user.age) {
        throw new ValidationError('No field: age');
    }
    if(!user.name) {
        throw new ValidationError('No field: name');
    }

    return user;
}

try {
    let user = readUser('{"age": 25}');
} catch(err) {
    if(err instanceof ValidationError) {
        alert('Invalid data:' + err.message); // Invalid data: No field: name
    } else if(err instanceof SyntaxError) {
        alert('JSSON Syntax Error:' + err.message);
    } else {
        throw err; //알려지지 않은 에러는 재던지기 한다.
    }
}
```

#### 더 깊게 상속하기

```javascript
class ValidationError extends Error {
    constructor(message) {
        super(message);
        this.name = 'ValidationError';
    }
}

class PropertyRequiredError extends ValidateionError {
    constructor(property) {
        super('No property:' + property);
        this.name = 'PropertyRequiredError';
        this.property = property;
    }
}

//사용법
function readUser(json) {
    let user = JSON.parse(json);

    if(!user.age) {
        throw new PropertyRequiredError('age');
    }
    if(!user.name) {
        throw new PropertyRequiredError('name');
    }

    return user;
}

try {
    let user = readUser('{"age": 25}');
} catch(err) {
    if(err instanceof ValidationError) {
        alert('Invalid data:' + err.message); // Invalid data: No property: name
        alert(err.name); // PropertyRequiredError
        alert(err.property); // name
    } else if(err instanceof SyntaxError) {
        alert('JSSON Syntax Error:' + err.message);
    } else {
        throw err; //알려지지 않은 에러는 재던지기 한다.
    }
}

```

#### 예외 감싸기

```javascript
class ReadError extends Error {
    constructor(message, cause) {
        super(message);
        this.cause = cause;
        this.name = 'ReadError';
    }
}

class ValidationError extends Errro ....
class PropertyRequiredError extends ValidationError ...

function validateUser(user) {
    if(!user.age) {
        throw new PropertyRequiredError('age');
    }

    if(!user.name) {
        throw new PropertyRequiredError('name');
    }
}

function readUser(json) {
    let user;

    try {
        user = JSON.parse(json);
    } catch (err) {
        if(err instanceof SyntaxError) {
            throw new ReadError('Syntax Error', err)
        } else {
            throw err;
        }
    }

    try {
        validateUser(user);
    } catch (err) {
        if(err instanceof ValidationError) {
            throw new ReadError('Validation Error', err);
        } else {
            throw err;
        }
    }
}

try {
    readUser('{잘못된 형식의 json}');
} catch (e) {
    if(e instanceof ReadError) {
        alert(e);
        //Original error: SyntaxError: Unexpected token b in JSON at position 1
        alert('Original error:' + e.cause)
    } else {
        throw e;
    }
}
```